apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-mastery-lab
  namespace: awx-mastery
spec:
  service_type: nodeport
  postgres_resource_requirements:
    requests:
      cpu: "100m"
      memory: "512Mi"
  web_resource_requirements:
    requests:
      cpu: "100m"
      memory: "512Mi"
