---
all:
  children:
    linux:
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
        secret_path: "lab/linux/{{ inventory_hostname }}"
      hosts:
        mahder05-redhat-rhel10:
        mahder05-ubuntu25-pro:
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_port: 5985
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
        secret_path: "lab/windows/{{ inventory_hostname }}"
      hosts:
        mahder05-windows11-pro: