---
- name: Hybrid Lab Connectivity Check
  hosts: hybrid_lab
  gather_facts: false
  
  pre_tasks:
    - name: Dynamically fetch credentials from Vault
      include_vars: vault_lookup.yml
      # This file now successfully finds VAULT_ADDR and tokens in the environment

  tasks:
    - name: Ping Linux
      ansible.builtin.ping:
      when: "'linux' in group_names"

    - name: Ping Windows
      ansible.windows.win_ping:
      when: "'windows' in group_names"