---
- name: Hybrid Lab Connectivity Check
  hosts: linux, windows
  gather_facts: false
  tasks:
    - name: Ping Linux
      ansible.builtin.ping:
      when: "'linux' in group_names"

    - name: Ping Windows
      ansible.windows.win_ping:
      when: "'windows' in group_names"