---
- name: Hybrid Lab - Linux
  hosts: linux
  gather_facts: false
  vars_files:
    - ../vars/vault_lookup_token.yml
  vars:
    secret_path: "lab/linux/{{ inventory_hostname }}"
    ansible_user: "{{ vault_kv2.data.data.username }}"
    ansible_password: "{{ vault_kv2.data.data.password }}"

  tasks:
    - name: Ping
      ping:

- name: Hybrid Lab - Windows
  hosts: windows
  gather_facts: false
  vars_files:
    - ../vars/vault_lookup.yml
  vars:
    secret_path: "lab/windows/{{ inventory_hostname }}"
    ansible_user: "{{ vault_kv2.data.data.username }}"
    ansible_password: "{{ vault_kv2.data.data.password }}"

  tasks:
    - name: Win ping
      ansible.windows.win_ping: