---
- name: Hybrid Lab - Linux Ping
  hosts: linux
  gather_facts: false
  tasks:
    - name: Fetch Linux Credentials
      include_vars:
        file: ../vars/vault_lookup.yml
      vars:
        # Pulls path from mahder05-ubuntu25-pro.yml, etc.
        secret_path: "{{ vault_secret_path }}"

    - name: Ping Linux
      ansible.builtin.ping:

- name: Hybrid Lab - Windows Ping
  hosts: windows
  gather_facts: false
  tasks:
    - name: Fetch Windows Credentials
      include_vars:
        file: ../vars/vault_lookup.yml
      vars:
        # Pulls path from mahder05-winserver2025.yml, etc.
        secret_path: "{{ vault_secret_path }}"

    - name: Win Ping
      ansible.windows.win_ping: